
# En tu repositorio de Git: config-repo/tax-service-docker.yml

server:
  port: 9092 # SERVER_PORT del contenedor

spring:
  application:
    name: tax-service
  
  #  CONFIGURACIN DE LA DB MOVILDA DESDE docker-compose 
  datasource:
    # El hostname correcto es db_tax
    url: jdbc:postgresql://db_tax:5432/db_tax 
    username: tax
    password: tax123
    driver-class-name: org.postgresql.Driver

# Configuraci贸n de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    enabled: true

# Configuraci贸n de Paginaci贸n (movida desde docker-compose)
pagination:
  default-page: 0
  default-size: 10
  max-size: 100
  default-sort-by: createdAt
  default-sort-dir: desc
  allowed-sort-fields: createdAt,updatedAt,name,rate

# Configuraci贸n de Actuator y Config Server Retry
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,beans
  endpoint:
    health:
      probes:
        enabled: true

spring:
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 3000
    refresh:
      enabled: false
